export let insuranceData = [
  {
    name: 'Life Insurance',
    title: 'Shanti-Amra Sobai',
    coverage: 100000,
    term: 5,
    Premium: 540,
    paymentMethod: 'Monthly',
    policyTerm: '12 months',
    stampFee: 100,
  },
  {
    name: 'Life Insurance',
    title: 'Shanti Sobai',
    coverage: 1000000,
    term: 5,
    Premium: 500,
    paymentMethod: 'Monthly',
    policyTerm: '12 months',
    stampFee: 100,
  },
  {
    name: 'Life Insurance',
    title: 'Shanti-Amra',
    coverage: 1000000,
    term: 5,
    Premium: 540,
    paymentMethod: 'Monthly',
    policyTerm: '12 months',
    stampFee: 100,
  },
  {
    name: 'Life Insurance',
    title: 'Shanti-Amra Sobai',
    coverage: 1000000,
    term: 5,
    Premium: 540,
    paymentMethod: 'Monthly',
    policyTerm: '12 months',
    stampFee: 100,
  },
  {
    name: 'Life Insurance',
    title: 'Shanti-Amra Sobai',
    coverage: 1000000,
    term: 5,
    Premium: 540,
    paymentMethod: 'Monthly',
    policyTerm: '12 months',
    stampFee: 100,
  },
  {
    name: 'Life Insurance',
    title: 'Shanti-Amra Sobai',
    coverage: 1000000,
    term: 5,
    Premium: 540,
    paymentMethod: 'Monthly',
    policyTerm: '12 months',
    stampFee: 100,
  },
];
